### ISSUE TITLE
Update to gradle 6.7.1

### ISSUE THREAD

**Issue by baywet** [rocklass/gradle-chocolatey-packages#42]
Gradle 6.7.1 has been available since November 16 https://gradle.org/install/.
Are you working on the new release or is it something you'd accept a pull request for?

**Comment by rocklass** [comment]
Hi @baywet, thanks for the issue, there was issue with my Gradle version tracker.

I just pushed the package on Chocolatey 

Enjoy ☕

**Comment by baywet** [comment]
thanks for the prompt resolution!
